version: '2.1'
jobs:
  deploy-app:
    docker:
    - image: cimg/base:current
    steps:
    - checkout
    - run:
        name: "Deploy Web App to Azure"
        command: |
          git remote add azure https://$GIT_USERNAME:$GIT_PASSWORD@azure-react-tutorial.scm.azurewebsites.net/azure-react-tutorial.git
          git branch -m master
          git push azure master --force
workflows:
  deploy:
    jobs:
      - deploy-app
